### ISSUE TITLE
Release Checklist - v0.1

### ISSUE THREAD

**Issue by TonyGrif** [TonyGrif/tempconverter#1]
## Features
- [ ] Convert between Fahrenheit and Celsius temperatures

## Build
- [ ] Use a Makefile to build the project
- [ ] Find a small unit testing framework for testing this project
- [ ] Create a GitHub workflow to automate testing this project
- [ ] Create a GitHub workflow to auto build and release this project on new tags
